version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20

  build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - api-blsheet/**/*
    - scripts/**/*
    - appspec.yml
  exclude-paths:
    - api-blsheet/node_modules/**/*   # ← don't ship node_modules
