const QUERY = {
  AUTH: {
    REGISTER: "REGISTER",
    LOGIN: "LOGIN",
    VERIFY_EMAIL_AND_CREATE_PASSWORD: "VERIFY_EMAIL_AND_CREATE_PASSWORD",
  },

  PROJECT: {
    GET_PROJECT: "GET_PROJECT",
    GET_PROJECTS: "GET_PROJECTS",
  },

  MEMBER: {
    GET_MEMBERS: "GET_MEMBERS",
  },

  TASK: {
    GET_TASKS: "GET_TASKS",
    GET_COMPLETED_TASKS: "GET_COMPLETED_TASKS",
    GET_COMPLETED_MEMBERS_TASKS: "GET_COMPLETED_MEMBERS_TASKS",
  },

  ISSUE: {
    GET_ISSUES: "GET_ISSUES",
    GET_ISSUE: "GET_ISSUE",
  },

  TEAM: {
    GET_TEAMS: "GET_TEAMS",
    GET_TEAM: "GET_TEAM",
  },

  DOC: {
    GET_DOC: "GET_DOC",
    GET_DOCS: "GET_DOCS",
  },

  LABEL: {
    GET_LABELS: "GET_LABELS",
  },

  CHAT: {
    CHANNEL: {
      GET_CHANNELS: "GET_CHANNELS",
      GET_CHANNEL: "GET_CHANNEL",
    },
    MESSAGE: {
      GET_MESSAGES: "GET_MESSAGES",
      GET_MESSAGE: "GET_MESSAGE",
    },
    CONVERSATION: {
      GET_CONVERSATIONS: "GET_CONVERSATIONS",
      GET_CONVERSATION: "GET_CONVERSATION",
    },
  },

  TIME_FRAME: {
    GET_TIME_FRAME: "GET_TIME_FRAME",
    GET_TIME_FRAMES: "GET_TIME_FRAMES",
  },

  OBJECTIVE: {
    GET_OBJECTIVE: "GET_OBJECTIVE",
    GET_OBJECTIVES: "GET_OBJECTIVES",
  },

  KEY_RESULT: {
    GET_KEY_RESULT: "GET_KEY_RESULT",
    GET_KEY_RESULTS: "GET_KEY_RESULTS",
  },

  SECRETE_KEY: {
    GET_SECRET_KEY: "GET_SECRET_KEY",
  },
};

export default QUERY;
