import { config } from 'dotenv'
config()

const {
  PORT,
  DB_URL,
  NODE_ENV,
  ACCESS_TOKEN_SECRET,
  FRONTEND_URL,
  MAIL_PORT,
  MAIL_HOST,
  MAIL_PASSWORD,
  MAIL_FROM,
  MAIL_USERNAME,
  CLOUD_NAME,
  CLOUD_API_KEY,
  CLOUD_API_SECRET,
  OPEN_AI_KEY,
  GROQ_API_KEY,
  OPENROUTER_API_KEY,
  TOP_K_MESSAGES,
} = process.env

const ENV = {
  PORT,
  DB_URL,
  NODE_ENV,
  ACCESS_TOKEN_SECRET,
  FRONTEND_URL,
  MAIL_PORT,
  MAIL_HOST,
  MAIL_PASSWORD,
  MAIL_FROM,
  MAIL_USERNAME,
  CLOUD_NAME,
  CLOUD_API_KEY,
  CLOUD_API_SECRET,
  OPEN_AI_KEY,
  GROQ_API_KEY,
  OPENROUTER_API_KEY,
  TOP_K_MESSAGES,
}

export default ENV
