const MSG = {
  DB_CONNECTED: 'Database connected successfully',

  AUTH: {
    SELF: 'SELF',
    USER_REGISTERED: 'USER_REGISTERED',
    USER_VERIFIED: 'USER_VERIFIED',
    USER_LOGGED_IN: 'USER_LOGGED_IN',
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
    RESET_PASSWORD: 'RESET_PASSWORD',
    USER_UPDATED_FULL_NAME: 'USER_UPDATED_FULL_NAME',
    USER_UPDATED_AVATAR: 'USER_UPDATED_AVATAR',
  },

  PROJECT: {
    GET_PROJECT: 'GET_PROJECT',
    UPDATE_PROJECT: 'UPDATE_PROJECT',
    CREATE_PROJECT: 'CREATE_PROJECT',
    DELETE_PROJECT: 'DELETE_PROJECT',
    GET_PROJECTS: 'GET_PROJECTS',
    UPDATE_OPENAI_KEY: 'UPDATE_OPENAI_KEY',
    REMOVE_OPENAI_KEY: 'REMOVE_OPENAI_KEY',
  },

  MEMBER: {
    GET_MEMBERS: 'GET_MEMBERS',
    GET_MEMBER: 'GET_MEMBER',
    CREATE_MEMBER: 'CREATE_MEMBER',
    UPDATE_MEMBER: 'UPDATE_MEMBER',
    REMOVE_MEMBER: 'REMOVE_MEMBER',
  },

  TEAM: {
    GET_TEAMS: 'GET_TEAMS',
    GET_TEAM: 'GET_TEAM',
    CREATE_TEAMS: 'CREATE_TEAMS',
    UPDATE_TEAMS: 'UPDATE_TEAMS',
    DELETE_TEAM: 'DELETE_TEAM',
    REMOVE_TEAMS: 'REMOVE_TEAMS',
    ADD_TEAM_MEMBER: 'ADD_TEAM_MEMBER',
    REMOVE_TEAM_MEMBER: 'REMOVE_TEAM_MEMBER',
    ADD_OR_REMOVE_TEAM_LEADER: 'ADD_OR_REMOVE_TEAM_LEADER',
  },

  TASK: {
    GET_TASKS: 'GET_TASKS',
    GET_TASK: 'GET_TASK',
    CREATE_TASK: 'CREATE_TASK',
    UPDATE_TASK: 'UPDATE_TASK',
    DELETE_TASK: 'DELETE_TASK',
    ASSIGN_MEMBER: 'ASSIGN_MEMBER',
    REMOVE_ASSINGED_MEMBER: 'REMOVE_ASSINGED_MEMBER',
    CREATE_COMMENT: 'CREATE_COMMENT',
    UPDATE_COMMENT: 'UPDATE_COMMENT',
    DELETE_COMMENT: 'DELETE_COMMENT',
    GET_LAST_30_DAYS_TASKS: 'GET_LAST_30_DAYS_TASKS',
    GET_USER_ASSIGNED_TASKS: 'GET_USER_ASSIGNED_TASKS',
    GET_MEMBERS_COMPLETED_TASKS: 'GET_MEMBERS_COMPLETED_TASKS',
  },

  ISSUE: {
    CREATE_ISSUE: 'CREATE_ISSUE',
    GET_ISSUE: 'GET_ISSUE',
    GET_ISSUES: 'GET_ISSUES',
    UPDATE_ISSUE: 'UPDATE_ISSUE',
    DELETE_ISSUE: 'DELETE_ISSUE',
    ASSIGN_MEMBER: 'ASSIGN_MEMBER',
    REMOVE_ASSIGNED_MEMBER: 'REMOVE_ASSIGNED_MEMBER',
    CREATE_COMMENT: 'CREATE_COMMENT',
    UPDATE_COMMENT: 'UPDATE_COMMENT',
    DELETE_COMMENT: 'DELETE_COMMENT',
  },

  DOCUMENT: {
    GET_DOCUMENTS: 'GET_DOCUMENTS',
    GET_DOCUMENT: 'GET_DOCUMENT',
    CREATE_DOCUMENT: 'CREATE_DOCUMENT',
    UPDATE_DOCUMENT: 'UPDATE_DOCUMENT',
    DELETE_DOCUMENT: 'DELETE_DOCUMENT',
    ASSIGN_MEMBER: 'ASSIGN_MEMBER',
    REMOVE_MEMBER: 'REMOVE_MEMBER',
  },

  CHAT: {
    CHANNEL: {
      GET_CHANNEL: 'GET_CHANNEL',
      GET_CHANNELS: 'GET_CHANNELS',
      UPDATE_CHANNEL: 'UPDATE_CHANNEL',
      DELETE_CHANNEL: 'DELETE_CHANNEL',
      CREATE_CHANNEL: 'CREATE_CHANNEL',
      ADD_MEMBER: 'ADD_MEMBER',
      REMOVE_MEMBER: 'REMOVE_MEMBER',
    },
    MESSAGE: {
      GET_MESSAGE: 'GET_MESSAGE',
      GET_MESSAGES: 'GET_MESSAGES',
      UPDATE_MESSAGE: 'UPDATE_MESSAGE',
      DELETE_MESSAGE: 'DELETE_MESSAGE',
      CREATE_MESSAGE: 'CREATE_MESSAGE',
    },
    REACTION: {
      ADD_REACTION: 'ADD_REACTION',
    },
    CONVERSATION: {
      GET_CONVERSATION: 'GET_CONVERSATION',
      DELETE_CONVERSATION: 'DELETE_CONVERSATION',
      GET_CONVERSATIONS: 'GET_CONVERSATIONS',
      CREATE_CONVERSATION: 'CREATE_CONVERSATION',
    },
  },

  TIME_FRAME: {
    GET_TIME_FRAME: 'GET_TIME_FRAME',
    GET_TIME_FRAMES: 'GET_TIME_FRAMES',
    CREATE_TIME_FRAME: 'CREATE_TIME_FRAME',
    DELETE_TIME_FRAME: 'DELETE_TIME_FRAME',
    UPDATE_TIME_FRAME: 'UPDATE_TIME_FRAME',
  },

  OBJECTIVE: {
    GET_OBJECTIVE: 'GET_OBJECTIVE',
    GET_OBJECTIVES: 'GET_OBJECTIVES',
    CREATE_OBJECTIVE: 'CREATE_OBJECTIVE',
    DELETE_OBJECTIVE: 'DELETE_OBJECTIVE',
    UPDATE_OBJECTIVE: 'UPDATE_OBJECTIVE',
  },

  KEY_RESULT: {
    GET_KEY_RESULT: 'GET_KEY_RESULT',
    GET_KEY_RESULTS: 'GET_KEY_RESULTS',
    CREATE_KEY_RESULT: 'CREATE_KEY_RESULT',
    DELETE_KEY_RESULT: 'DELETE_KEY_RESULT',
    UPDATE_KEY_RESULT: 'UPDATE_KEY_RESULT',
    UPDATE_CURRENT_VALUE: 'UPDATE_CURRENT_VALUE',
  },

  ASSESSMENT: {
    GET_ASSESSMENT: 'GET_ASSESSMENT',
    CREATE_ASSESSMENT: 'CREATE_ASSESSMENT',
    UPDATE_ASSESSMENT: 'UPDATE_ASSESSMENT',
    DELETE_ASSESSMENT: 'DELETE_ASSESSMENT',
    GET_ASSESSMENTS: 'GET_ASSESSMENTS',
    PUBLISH_ASSESSMENT: 'PUBLISH_ASSESSMENT',
    ASSIGN_OR_REMOVE_MEMBER: 'ASSIGN_OR_REMOVE_MEMBER',
    GET_ASSINGED_ASSESSMENT: 'GET_ASSINGED_ASSESSMENT',
    GET_ASSINGED_ASSESSMENTS: 'GET_ASSINGED_ASSESSMENTS',
    CATEGORY: {
      GET_CATEGORY: 'GET_CATEGORY',
      CREATE_CATEGORY: 'CREATE_CATEGORY',
      UPDATE_CATEGORY: 'UPDATE_CATEGORY',
      DELETE_CATEGORY: 'DELETE_CATEGORY',
      GET_CATEGORIES: 'GET_CATEGORIES',
    },
    QUESTION: {
      GET_QUESTION: 'GET_QUESTION',
      CREATE_QUESTION: 'CREATE_QUESTION',
      UPDATE_QUESTION: 'UPDATE_QUESTION',
      DELETE_QUESTION: 'DELETE_QUESTION',
      GET_QUESTIONS: 'GET_QUESTIONS',
    },
    RESPONSE: {
      GET_RESPONSE: 'GET_RESPONSE',
      START_ASSESSMENT: 'START_ASSESSMENT',
      SUBMIT_ASSESSMENT: 'SUBMIT_ASSESSMENT',
    },
  },

  SECRET_KEY: {
    GET_SECRET_KEY: 'GET_SECRET_KEY',
    UPDATE_SECRET_KEY: 'UPDATE_SECRET_KEY',
    DELETE_SECRET_KEY: 'DELETE_SECRET_KEY',
    CREATE_SECRET_KEY: 'CREATE_SECRET_KEY',
  },

  LLM: {
    ERROR_CALL_TO_LLM: 'ERROR_CALL_TO_LLM',
    PROCESS_USER_INPUT_ERROR: 'PROCESS_USER_INPUT_ERROR',
    ERROR_WHILE_STREAM_RESPONSE: 'ERROR_WHILE_STREAM_RESPONSE',
    GENERATE_RESPONSE: 'GENERATE_RESPONSE',
    GET_PROJECTS_LIST: 'GET_PROJECT_LIST',
  },
}

export default MSG
